version: '3.8'

services:
  web:
    build: ./
    command: uvicorn project.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - SECRET_KEY=supersecreto
      - DATABASE_NAME=empleados_dev
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=web-db
      - DATABASE_PORT=5432
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pg_data: